### PR TITLE
Merge code with version of rainbow.me and fix rendering and crashes on android.

### PR DESCRIPTION
**Pull request by outaTiME**
Hi @osdnk, 
I was stabilizing this component for Android a bit, firstly I made a merge with the rainbow.me version and secondly I made some adjustments (along with some comments) in the `ChartPath.js`.

Inside `setoriginalXYAccordingToPosition` I added a condition to avoid crashes in android, and then in the `useAnimatedGestureHandler` modify the `onStart` to be aligned with `onActive` which in android experienced different renders than in iOS.

I hope it is useful and that you can merge it with the master.

### CODE REVIEW

**Comment by osdnk** [comment]
Hey, I did this

**Comment by outaTiME** [comment]
wow, amazing, I had already forgotten about this PR, I was using my own source code, now I can use your package again, thanks in advance !! 🥰

**Comment by outaTiME** [comment]
I see that in the code that is in the master you forgot to include the `yRange` in the parse of the `ChartPath.js` (in the documentation as well).

https://github.com/outaTiME/react-native-animated-charts/blob/93db4fcbbb8a344bd2e6a926cae87d6bf8e5c57b/src/charts/linear/ChartPath.js#L61

You probably forgot when you used the rainbow code in my PR was that, could you add it again?

**Comment by outaTiME** [comment]
And another thing I see that you accepted my pull request but you overwrote everything with all your changes to the rainbow version, that is precisely why the `yRange` was lost and some fixes that I had made to solve crashes in android were also lost, I had even left comments so that you are aware of each of the problems that it had detected.

It would be very useful if you could verify or else I try to make a new PR with the fixes in the version you left, but I am afraid to do it and that in the next merge with rainbow they will be lost again.

**Comment by osdnk** [comment]
Hey, 
I am sorry. It was my mistake. Can you reapply your changes?
I got a bit lost in a codebase yesterday, but I want to have those changes

**Comment by outaTiME** [comment]
No problem, 
I need some free time and close some pending issues to prepare the PR again, you will have news shortly 🙌

**Comment by outaTiME** [comment]
Done, 
I create a new PR with your master version and with what I had done last time 🤗

**Pull request closed without merging**
